server: 
  port: 7070 
spring: 
  application: 
    name: student-service 
    
eureka: 
  client: 
    fetch-registry: false 
    register-with-eureka: false
    service-url: 
      defaultZone: http://localhost:8761/eureka